### ISSUE TITLE
The Poster screen is not properly unmounted when navigating back while downloading a poster

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/pauling#31]
## Purpose

While downloading a poster (Poster Screen), switching back to the Poster list will warn you as follow:

![image](https://user-images.githubusercontent.com/956157/29420349-0de631f6-8372-11e7-84c9-a13987a8631c.png)

It seems that the downloading process prevents component unmounting.

## Proposal

Explicitly abort the download process when unmounting the current `Poster`.

**Comment by willdurand** [comment]
Looks like it has been fixed, cannot reproduce it.
