### ISSUE TITLE
Display placeholders for thumbnails being processed

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/pauling#44]
## Purpose

For big (heavy) posters, thumbnails processing may take some time. A blank block is displayed instead of the poster picture (poster list).

## Proposal

Why not add a placeholder with an icon instead?

**Comment by willdurand** [comment]
Can you be more precise? What is taking time? Thumbnails are not processed IIRC.

**Comment by jmaupetit** [comment]
You are right. Closing this as I think it might be finally related to #47.
