### ISSUE TITLE
Remove poster drop shadow in PosterScreen

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/pauling#66]
## Purpose

I don't like the PosterScreen's drop shadow effect on poster. I think it does not fit well with the view style.

![image-1](https://user-images.githubusercontent.com/956157/31599347-51ffc74e-b252-11e7-93e9-3f5b4cf3439d.jpg)

## Proposal

Remove the drop shadow effect in favor of a darker background.

**Comment by willdurand** [comment]
I believe this is a wontfix since it is inside a native webview.

**Comment by jmaupetit** [comment]
😢 Using a dark background will limit the effect. WDYT?

**Comment by willdurand** [comment]
I don't think it is feasible as it is the native PDF viewer in the native webview.

**Comment by willdurand** [comment]
marking as wontfix sorry, this is not feasible right now but I have a plan for v2.
