### ISSUE TITLE
PosterScreen: sometimes the poster is not displayed

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/pauling#67]
## Purpose

When navigating back & forth from the `AppScreen` to a `PosterScreen`, sometimes, the poster from the `PosterScreen` is not rendered:

![img_5036](https://user-images.githubusercontent.com/956157/31599533-26666cd6-b253-11e7-9ddf-7ed433cb323e.PNG)

## Proposal

We need to investigate  :shipit:

**Comment by willdurand** [comment]
This should be fixed in 1.4.0 🎉
